# Generated by Django 3.2 on 2021-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('cam_id', models.AutoField(primary_key=True, serialize=False)),
                ('cam_location', models.CharField(max_length=30)),
                ('cam_ip', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
