# Generated by Django 3.2 on 2021-05-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_cctv_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='cam_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
