# Generated by Django 3.2 on 2021-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_alter_cctv_cam_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cctv',
            name='cam_location',
            field=models.CharField(default='설치 위치를 입력하세요', max_length=30),
        ),
    ]
