# Generated by Django 3.2 on 2021-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_rename_record_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
