# Generated by Django 3.2 on 2021-05-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_rename_records_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='file_name',
            new_name='file_path',
        ),
    ]
