# Generated by Django 3.2 on 2021-05-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0008_rename_cam_id_cctv_cam_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cctv',
            old_name='cam_num',
            new_name='cam_id',
        ),
    ]
