# Generated by Django 3.2 on 2021-05-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
        ('users', '0002_alter_account_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cam_id',
            field=models.ForeignKey(db_column='cam_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv', to='cctv.cctv'),
        ),
    ]
